In [89]:
import pandas as pd
import numpy as np

In [90]:
df = pd.read_csv("C:\\project2\\Data-Analytics-Project2\\data\\sales.csv")
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_12628\2498604383.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:\\project2\\Data-Analytics-Project2\\data\\sales.csv")

,order_id,order_date,status,item_id,sku,qty_ordered,price,discount_amount,category,payment_method,...,Customer Since,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name
0,100354678,01-10-2020,received,574772,oasis_Oasis-064-36,21,89.9,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus
1,100354678,01-10-2020,received,574774,Fantastic_FT-48,11,19.0,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus
2,100354680,01-10-2020,complete,574777,mdeal_DMC-610-8,9,149.9,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus
3,100354680,01-10-2020,complete,574779,oasis_Oasis-061-36,9,79.9,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus
4,100367357,13-11-2020,received,595185,MEFNAR59C38B6CA08CD,2,99.9,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus

In [227]:
df.isnull().sum()

order_id           0
order_date         0
status             0
item_id            0
sku                0
qty_ordered        0
price              0
discount_amount    0
category           0
payment_method     0
bi_st              0
cust_id            0
year               0
month              0
ref_num            0
Name Prefix        0
First Name         0
Middle Initial     0
Last Name          0
Gender             0
age                0
full_name          0
E Mail             0
Customer Since     0
SSN                0
Phone No.          0
Place Name         0
County             0
City               0
State              0
Zip                0
Region             0
User Name          0
dtype: int64

In [243]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [244]:
# Convert Date Columns
df["order_date"] = pd.to_datetime(
    df["order_date"],
    errors="coerce",
    dayfirst=True
)

df["Customer Since"] = pd.to_datetime(
    df["Customer Since"],
    errors="coerce"
)

In [259]:
df.dtypes

order_id                   object
order_date         datetime64[ns]
status                     object
item_id                     int64
sku                        object
qty_ordered                 int64
price                     float64
discount_amount           float64
category                   object
payment_method             object
bi_st                      object
cust_id                     int64
year                        int64
month                      object
ref_num                     int64
Name Prefix                object
First Name                 object
Middle Initial             object
Last Name                  object
Gender                     object
age                         int64
full_name                  object
E Mail                     object
Customer Since     datetime64[ns]
SSN                        object
Phone No.                  object
Place Name                 object
County                     object
City                       object
State                      object
Zip                         int64
Region                     object
User Name                  object
dtype: object

In [273]:
df[["order_date", "Customer Since"]].head()

  order_date Customer Since
0 2020-10-01     2006-08-22
1 2020-10-01     2006-08-22
2 2020-10-01     2006-08-22
3 2020-10-01     2006-08-22
4 2020-11-13     2006-08-22

In [286]:
df[["order_date", "Customer Since"]].isnull().sum()

order_date        0
Customer Since    0
dtype: int64

In [288]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286392 entries, 0 to 286391
Data columns (total 33 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_id         286392 non-null  object
 1   order_date       286392 non-null  datetime64[ns]
 2   status           286392 non-null  object
 3   item_id          286392 non-null  int64
 4   sku              286392 non-null  object
 5   qty_ordered      286392 non-null  int64
 6   price            286392 non-null  float64
 7   discount_amount  286392 non-null  float64
 8   category         286392 non-null  object
 9   payment_method   286392 non-null  object
 10  bi_st            286392 non-null  object
 11  cust_id          286392 non-null  int64
 12  year             286392 non-null  int64
 13  month            286392 non-null  object
 14  ref_num          286392 non-null  int64
 15  Name Prefix      286392 non-null  object
 16  First Name       286392 non-null  object
 17  Middle Initial   286392 non-null  object
 18  Last Name        286392 non-null  object
 19  Gender           286392 non-null  object
 20  age              286392 non-null  int64
 21  full_name        286392 non-null  object
 22  E Mail           286392 non-null  object
 23  Customer Since   286392 non-null  datetime64[ns]
 24  SSN              286392 non-null  object
 25  Phone No.        286392 non-null  object
 26  Place Name       286392 non-null  object
 27  County           286392 non-null  object
 28  City             286392 non-null  object
 29  State            286392 non-null  object
 30  Zip              286392 non-null  int64
 31  Region           286392 non-null  object
 32  User Name        286392 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(7), object(22)
memory usage: 72.1+ MB

In [298]:
df.shape

(286392, 33)