In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("C:\\project2\\Data-Analytics-Project2\\data\\sales.csv")
df.head()

C:\Users\admin\AppData\Local\Temp\ipykernel_4920\2498604383.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:\\project2\\Data-Analytics-Project2\\data\\sales.csv")

,order_id,order_date,status,item_id,sku,qty_ordered,price,discount_amount,category,payment_method,...,Customer Since,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name
0,100354678,01-10-2020,received,574772,oasis_Oasis-064-36,21,89.9,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus
1,100354678,01-10-2020,received,574774,Fantastic_FT-48,11,19.0,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus
2,100354680,01-10-2020,complete,574777,mdeal_DMC-610-8,9,149.9,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus
3,100354680,01-10-2020,complete,574779,oasis_Oasis-061-36,9,79.9,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus
4,100367357,13-11-2020,received,595185,MEFNAR59C38B6CA08CD,2,99.9,0.0,Men's Fashion,cod,...,8/22/2006,627-31-5251,405-959-1129,Vinson,Harmon,Vinson,OK,73571,South,jwtitus

In [5]:
df.isnull().sum()

order_id           0
order_date         0
status             0
item_id            0
sku                0
qty_ordered        0
price              0
discount_amount    0
category           0
payment_method     0
bi_st              0
cust_id            0
year               0
month              0
ref_num            0
Name Prefix        0
First Name         0
Middle Initial     0
Last Name          0
Gender             0
age                0
full_name          0
E Mail             0
Customer Since     0
SSN                0
Phone No.          0
Place Name         0
County             0
City               0
State              0
Zip                0
Region             0
User Name          0
dtype: int64

In [6]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [7]:
# Convert Date Columns
df["order_date"] = pd.to_datetime(
    df["order_date"],
    errors="coerce",
    dayfirst=True
)

df["Customer Since"] = pd.to_datetime(
    df["Customer Since"],
    errors="coerce"
)

In [8]:
df.dtypes

order_id                   object
order_date         datetime64[ns]
status                     object
item_id                     int64
sku                        object
qty_ordered                 int64
price                     float64
discount_amount           float64
category                   object
payment_method             object
bi_st                      object
cust_id                     int64
year                        int64
month                      object
ref_num                     int64
Name Prefix                object
First Name                 object
Middle Initial             object
Last Name                  object
Gender                     object
age                         int64
full_name                  object
E Mail                     object
Customer Since     datetime64[ns]
SSN                        object
Phone No.                  object
Place Name                 object
County                     object
City                       object
State                      object
Zip                         int64
Region                     object
User Name                  object
dtype: object

In [9]:
df[["order_date", "Customer Since"]].head()

  order_date Customer Since
0 2020-10-01     2006-08-22
1 2020-10-01     2006-08-22
2 2020-10-01     2006-08-22
3 2020-10-01     2006-08-22
4 2020-11-13     2006-08-22

In [10]:
df[["order_date", "Customer Since"]].isnull().sum()

order_date             0
Customer Since    111104
dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286392 entries, 0 to 286391
Data columns (total 33 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   order_id         286392 non-null  object
 1   order_date       286392 non-null  datetime64[ns]
 2   status           286392 non-null  object
 3   item_id          286392 non-null  int64
 4   sku              286392 non-null  object
 5   qty_ordered      286392 non-null  int64
 6   price            286392 non-null  float64
 7   discount_amount  286392 non-null  float64
 8   category         286392 non-null  object
 9   payment_method   286392 non-null  object
 10  bi_st            286392 non-null  object
 11  cust_id          286392 non-null  int64
 12  year             286392 non-null  int64
 13  month            286392 non-null  object
 14  ref_num          286392 non-null  int64
 15  Name Prefix      286392 non-null  object
 16  First Name       286392 non-null  object
 17  Middle Initial   286392 non-null  object
 18  Last Name        286392 non-null  object
 19  Gender           286392 non-null  object
 20  age              286392 non-null  int64
 21  full_name        286392 non-null  object
 22  E Mail           286392 non-null  object
 23  Customer Since   175288 non-null  datetime64[ns]
 24  SSN              286392 non-null  object
 25  Phone No.        286392 non-null  object
 26  Place Name       286392 non-null  object
 27  County           286392 non-null  object
 28  City             286392 non-null  object
 29  State            286392 non-null  object
 30  Zip              286392 non-null  int64
 31  Region           286392 non-null  object
 32  User Name        286392 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(7), object(22)
memory usage: 72.1+ MB

In [12]:
df.shape

(286392, 33)

In [13]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df["Customer Since"] = pd.to_datetime(df["Customer Since"], errors="coerce")

In [14]:
df["Sales"] = (df["qty_ordered"] * df["price"]) - df["discount_amount"]

df[["qty_ordered", "price", "discount_amount", "Sales"]].head()

   qty_ordered  price  discount_amount   Sales
0           21   89.9              0.0  1887.9
1           11   19.0              0.0   209.0
2            9  149.9              0.0  1349.1
3            9   79.9              0.0   719.1
4            2   99.9              0.0   199.8

In [15]:
df.describe()

,order_date,item_id,qty_ordered,price,discount_amount,cust_id,year,ref_num,age,Customer Since,Zip,Sales
count,286392,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,286392.000000,175288,286392.000000,286392.000000
mean,2021-03-12 11:18:32.008715264,741664.902131,3.011296,851.385253,70.039427,70048.019054,2020.618778,560853.663395,46.489033,2007-11-04 18:25:55.602209280,49723.160015,1667.225760
min,2020-10-01 00:00:00,574769.000000,1.000000,0.000000,0.000000,4.000000,2020.000000,111127.000000,18.000000,1978-11-30 00:00:00,210.000000,0.000000
25%,2020-12-24 00:00:00,659684.500000,2.000000,49.900000,0.000000,56519.000000,2020.000000,341265.000000,32.000000,2002-10-17 00:00:00,26571.750000,119.800000
50%,2021-03-16 00:00:00,742309.000000,2.000000,119.000000,0.000000,74225.500000,2021.000000,564857.000000,47.000000,2010-03-21 00:00:00,49316.000000,313.967000
75%,2021-05-18 00:00:00,826124.250000,3.000000,950.000000,18.383050,92357.000000,2021.000000,781086.000000,61.000000,2015-01-17 00:00:00,72645.000000,1935.000000
max,2021-09-30 00:00:00,905208.000000,501.000000,101262.590000,30213.150000,115326.000000,2021.000000,999981.000000,75.000000,2017-07-28 00:00:00,99950.000000,202525.180000
std,NaN,95746.031827,4.573837,1741.750751,256.880870,30243.856395,0.485688,255828.418398,16.673288,NaN,27597.198873,3506.053973

In [16]:
total_revenue = df["Sales"].sum()

print(f"Total Revenue: ₹{total_revenue:,.2f}")

Total Revenue: ₹477,480,119.92

In [17]:
total_orders = df["order_id"].nunique()

print("Total Orders:", total_orders)

Total Orders: 201716

In [18]:
total_customers = df["cust_id"].nunique()

print("Total Customers:", total_customers)

Total Customers: 64248

In [19]:
average_order_value = total_revenue / total_orders

print(f"Average Order Value: ₹{average_order_value:.2f}")

Average Order Value: ₹2367.09

In [20]:
df["status"].value_counts()

status
canceled          112166
complete           88968
received           51775
order_refunded     25713
refund              3820
cod                 2851
paid                 756
closed               176
payment_review        57
pending               48
processing            33
holded                25
pending_paypal         4
Name: count, dtype: int64

In [21]:
df["category"].value_counts().head(10)

category
Mobiles & Tablets    61761
Men's Fashion        40713
Appliances           33034
Women's Fashion      28334
Others               26108
Beauty & Grooming    17899
Entertainment        17352
Superstore           15024
Home & Living        13990
Health & Sports       8421
Name: count, dtype: int64

In [22]:
df["payment_method"].value_counts()

payment_method
cod                  102916
Easypay               69679
Payaxis               31049
easypay_voucher       29763
bankalfalah           23057
Easypay_MA            11536
jazzwallet             6669
jazzvoucher            6045
customercredit         3702
apg                    1758
mcblite                 208
cashatdoorstep            9
financesettlement         1
Name: count, dtype: int64

In [23]:
df["State"].value_counts().head(10)

State
TX    17510
CA    17130
NY    15567
PA    14394
IL    12628
FL    10538
OH    10204
MO     8876
VA     8557
IA     8170
Name: count, dtype: int64

In [24]:
df["City"].value_counts().head(10)

City
Dekalb           2525
Washington       2008
New York City    1391
Houston          1250
El Paso          1019
Atlanta           999
Dallas            838
Springfield       817
Albany            726
Kittanning        716
Name: count, dtype: int64

In [25]:
print("----- Business Insights -----")
print(f"Total Revenue       : ₹{total_revenue:,.2f}")
print(f"Total Orders        : {total_orders}")
print(f"Total Customers     : {total_customers}")
print(f"Average Order Value : ₹{average_order_value:.2f}")

----- Business Insights -----
Total Revenue       : ₹477,480,119.92
Total Orders        : 201716
Total Customers     : 64248
Average Order Value : ₹2367.09

In [26]:
cohort_df = df[["cust_id", "order_id", "order_date"]].copy()

cohort_df.head()

   cust_id   order_id order_date
0    60124  100354678 2020-10-01
1    60124  100354678 2020-10-01
2    60124  100354680 2020-10-01
3    60124  100354680 2020-10-01
4    60124  100367357 2020-11-13

In [27]:
cohort_df = cohort_df.dropna(subset=["order_date"])

cohort_df.shape

(286392, 3)

In [ ]:
# Create Order Month
cohort_df["OrderMonth"] = cohort_df["order_date"].dt.to_period("M")

cohort_df.head()

   cust_id   order_id order_date OrderMonth
0    60124  100354678 2020-10-01    2020-10
1    60124  100354678 2020-10-01    2020-10
2    60124  100354680 2020-10-01    2020-10
3    60124  100354680 2020-10-01    2020-10
4    60124  100367357 2020-11-13    2020-11

In [ ]:
# Find First Purchase Month
cohort_df["CohortMonth"] = cohort_df.groupby("cust_id")["OrderMonth"].transform("min")

cohort_df.head()

   cust_id   order_id order_date OrderMonth CohortMonth
0    60124  100354678 2020-10-01    2020-10     2020-10
1    60124  100354678 2020-10-01    2020-10     2020-10
2    60124  100354680 2020-10-01    2020-10     2020-10
3    60124  100354680 2020-10-01    2020-10     2020-10
4    60124  100367357 2020-11-13    2020-11     2020-10

In [30]:
cohort_df.sample(10)

        cust_id   order_id order_date OrderMonth CohortMonth
144046    40816  100508841 2021-05-02    2021-05     2020-12
268590   110189  100538008 2021-07-04    2021-07     2021-07
37855     19175  100422388 2020-12-28    2020-12     2020-11
259162    46736  100557661 2021-09-15    2021-09     2021-06
111051    71767  100396900 2020-12-22    2020-12     2020-12
181447    86455  100469248 2021-04-03    2021-04     2021-03
255024   107364  100523299 2021-06-11    2021-06     2021-06
93495     12351  100484840 2021-04-19    2021-04     2020-12
208460    92634  100470755 2021-04-04    2021-04     2021-04
15248      9358  100469158 2021-04-03    2021-04     2020-10